name: CI
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository
      - uses: actions/checkout@v3

      - name: Display OS name
        run: echo "OS name & details is " $(lsb_release -a 2>/dev/null | cut  -f 2 | sed -n '2p')
        
      - name: List the files in the repository
        run: |
          ls ${{ github.workspace }}
